#!/usr/bin/env bash

declare -i _arg_idx=0
declare -ra _args=("$@")

function peek() {
    echo "${_args+${_args[${_arg_idx}]}}"
}

function build() {
    echo "Building latest container from local"
    docker-compose build
}

function push() {
    echo "Pushing docker container to remote"
    docker-compose push
}

function deploy() {
    echo "Creating deployment"
}

function top() {
    local -r token=$(peek)

    case "${token}" in
        build)
            build
            ;;
        push)
            push
            ;;
        deploy)
            deploy
            ;;
        *)
    esac
}

top
