FROM tiangolo/uwsgi-nginx-flask:python3.8
RUN apt-get update && apt-get install -y ca-certificates
RUN mkdir /substrate-api
WORKDIR /substrate-api
COPY requirements.txt ./
RUN pip install -r requirements.txt
COPY nginx.conf /app/
COPY . .
RUN chmod +x main.py
