FROM tiangolo/uwsgi-nginx-flask:python3.8
RUN apt-get update && apt-get install -y ca-certificates
RUN mkdir /kusama-api
WORKDIR /kusama-api
COPY requirements.txt ./
RUN pip install -r requirements.txt
COPY . .
RUN chmod +x main.py
